- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
- uhdm-tests/opentitan/Makefile.in
This PR fixes building earlgrey bitstream using UHDM plugin.
> Fix building earlgrey bitstream

- uhdm-tests/opentitan/Makefile.in
> opentitan: move gpio to uhdm

- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
- uhdm-tests/opentitan/Makefile.in
Add:
```
ibex_icache.sv
ibex_dummy_instr.sv
sram2tlul.sv
aes_core.sv
aes_reg_pkg.sv
aes_reg_top.sv
aes_sbox.sv
aes_sbox_lut.sv
aes_sbox_canright.sv
aes_sbox_canright_masked_noreuse.sv
aes_sbox_canright_masked.sv
aes.sv
```
to UHDM.
Related change in the plugin: https://github.com/antmicro/yosys-symbiflow-plugins/pull/10
> Add AES modules (and a few others)

- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
- uhdm-tests/opentitan/Makefile.in
> Move padctrl_reg_top and padctrl modules to uhdm

- .github/workflows/main.yml
This PR also disables failing tests for now. They needs to be fixed and enabled again.
> Bump UHDM-integration-tests

- uhdm-tests/ibex/top_artya7_core.patch
This PR includes patch to workaround dual memory issue in yosys.
> Update ibex repository

- .github/workflows/main.yml
- .gitmodules
- uhdm-tests/swerv/0001-swerv.patch
- uhdm-tests/swerv/Makefile.in
> Add initial support for SweRV core

- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
- uhdm-tests/opentitan/Makefile.in
Move alert_handler, top_earlgrey, clkgen, jtag_mux and top_earlgrey_nexysvideo to UHDM.
Fixes: https://github.com/chipsalliance/UHDM-integration-tests/issues/277
Fixes: https://github.com/chipsalliance/UHDM-integration-tests/issues/218
Now all modules are only parsed by UHDM.
> Move alert_handler, top_earlgrey, clkgen,  jtag_mux and top_earlgrey_nexysvideo to UHDM

- .github/workflows/main.yml
- build_binaries.sh
- uhdm-tests/opentitan/Makefile.in
> CI: use self-hosted runners

- .gitmodules
> Change yosys-symbiflow-plugins repository to Symbiflow

- uhdm-tests/swerv/0001-swerv.patch
> Update swerv patch

- build_binaries.sh
> Add option to skip building yosys

- .github/workflows/main.yml
> Use ccache to speedup builds

- README.rst
> Add initial version of README

- build_binaries.sh
> Add option to build sv2v (default skip)

- .github/workflows/main.yml
> Set DEBIAN_FRONTEND to noninteractive

- .github/workflows/main.yml
- uhdm-tests/swerv/0001-swerv.patch
> Bump Surelog

- uhdm-tests/swerv/Makefile.in
> Pin fusesoc version

- .github/workflows/main.yml
- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
Requires: https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/185, https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/187
> Update opentitan patch

- .github/workflows/main.yml
- .gitmodules
- build_binaries.sh
- yosys-patches/0001-Add-support-for-typedef-with-range-in-struct.patch
- yosys-patches/0002-Add-support-for-accessing-whole-struct.patch
- yosys-patches/0003-Add-always_comb_nolatch_5-test.patch
- yosys-patches/0004-Always-look-for-variables-for-nosync.patch
Requires: https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/186
> Remove BUILD_UPSTREAM variable

- .github/dependabot.yml
> Increase maximum open pull requrest limit

- .github/workflows/main.yml
- install_plugin.sh
Add plugin-only releases to make it easier for people to use the plugin.
Signed-off-by: Krzysztof Bieganski <kbieganski@antmicro.com>
> Add plugin-only releases

- .github/workflows/main.yml
> Use debian to test plugin install

- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
> Add -noclkbuf to yosys_synth_options

- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
This PR updates opentitan and Surelog.
Requires: https://github.com/SymbiFlow/yosys-f4pga-plugins/pull/240
> Bump opentitan and Surelog

- uhdm-tests/opentitan/Makefile.in
> Bump opentitan

- .github/workflows/main.yml
> Use highmem machines in opentitan synth

- .gitmodules
> Update yosys-f4pga-plugins url

- .github/workflows/main.yml
- build_binaries.sh
Separated from https://github.com/antmicro/yosys-uhdm-plugin-integration/pull/913.
> Run yosys plugin with address sanitizer

- .github/workflows/main.yml
It started failing in the CI on the main branch.
> Add libreadline to plugin installation step

- .github/workflows/main.yml
CI on the main branch seems to be red because of the lack of this.
> Install libreadline7

- .github/scripts/bisect.sh
- .github/scripts/common.sh
- .github/workflows/main.yml
Draft PR to see how much work it will be.
> Bump Ubuntu to newer LTS

- .github/workflows/tuttest.yml
- README.rst
Signed-off-by: Joanna Brozek <jbrozek@antmicro.com>
> README.rst: Add example of how to parse multiple files

- .github/workflows/main.yml
- formal/formal_results.py
- formal_verification.py
Signed-off-by: Rafal Kapuscik <rkapuscik@antmicro.com>
> Print formal verification summary

- .github/scripts/bisect.sh
- .github/scripts/common.sh
- .github/workflows/main.yml
> Install missing libtinfo5 in synth jobs

- formal/passlist.txt
Signed-off-by: Rafal Kapuscik <rkapuscik@antmicro.com>
> Bump plugins, update passlist

- formal/passlist.txt
This PR tests the changes in _systemverilog-plugin_ done in this PR: https://github.com/chipsalliance/yosys-f4pga-plugins/pull/425
> Visit vpiContAssign only in uhdmtopModules

- .github/workflows/main.yml
- .gitmodules
- uhdm-tests/opentitan/0001-add-Core-files-for-processing-Earlgrey-in-Yosys.patch
- uhdm-tests/opentitan/0001-allow-processing-cores-without-top-module.patch
- uhdm-tests/opentitan/0002-use-Edalize-fork-for-SystemVerilog-in-Yosys.patch
- uhdm-tests/opentitan/Makefile.in
- uhdm-tests/opentitan/iterate_cores.py
This bumps OpenTitan to a newer revision (`748b19f8aa4bcd9b7c077d37b5f042dd23e07b23`).
In order to provide information about what parts of the codebase are not parsed by the plugin correctly, there's a script which executes FuseSoC on each Core file separately.
The results can be seen in CI: https://github.com/antmicro/yosys-systemverilog/actions/runs/3829568138#summary-10412344611
If a dependency of a core file wasn't parsed sucessfully (status: FAILED), the core is skipped without executing FuseSoC.
There's also a dependency graph with nodes colored depending on the status: https://github.com/antmicro/yosys-systemverilog/actions/runs/3829568138#artifacts
FuseSoC expects each and every Core selected as the build target to have a `toplevel` defined. This makes sense for synthesis, but …
> OpenTitan update

- .github/workflows/main.yml
- uhdm-tests/opentitan/ot-cores-passlist.txt
Here's a flow to test the changes with unexpected passes:
https://github.com/antmicro/yosys-systemverilog/actions/runs/4053171175
> OpenTitan: fail when tests unexpectedly fail or pass

- .github/workflows/main.yml
With this change, the releases should get a prettier name and a proper description.
Signed-off-by: Tomasz Gorochowik <tgorochowik@antmicro.com>
> Improve release details

- .github/workflows/large-designs.yml
- .gitmodules
- uhdm-tests/opentitan/0001-Add-core-files-for-processing-Earlgrey-in-Yosys.patch
- uhdm-tests/opentitan/Makefile.in
- uhdm-tests/opentitan/iterate_cores.py
- uhdm-tests/opentitan/ot-cores-passlist.txt
Changes in results:
```diff
-lowrisc:ip:adc_ctrl:1.0                        DEPENDENCY_FAILED
-lowrisc:ip:aes:1.0                             DEPENDENCY_FAILED
-lowrisc:ip:csrng:0.1                           DEPENDENCY_FAILED
-lowrisc:ip:entropy_src:0.1                     DEPENDENCY_FAILED
-lowrisc:ip:entropy_src_ack_sm_pkg:0.1          PASSED
-lowrisc:ip:entropy_src_main_sm_pkg:0.1         PASSED
-lowrisc:ip:hmac:0.1                            DEPENDENCY_FAILED
-lowrisc:ip:keymgr:0.1                          DEPENDENCY_FAILED
-lowrisc:ip:pwm:0.1                             DEPENDENCY_FAILED
-lowrisc:ip:spi_device:0.1                      DEPENDENCY_FAILED
-lowrisc:prim:msb_extend:0                      PASSED
-lowrisc:prim:sum_tree:0                        PASSED …
```
> CI: Switch Opentitan to "custom tiny" in the parsing test.

- .github/workflows/main.yml
- .github/workflows/tuttest.yml
This is test PR. It doesn't target master branch but test branch.
> MERGE QUEUE TEST: Test PR

- uhdm-tests/opentitan/opentitan_parsing_test/ot-cores-passlist.txt
Update OpenTitan with fixes for core dependencies. We have a few new passing cores.
> bump opentitan submodule

- .github/workflows/large-designs.yml
- .github/workflows/parsing-tests.yml
- .gitmodules
- uhdm-tests/black-parrot/0001-Replace-stream-op.patch
- uhdm-tests/black-parrot/0002-Use-typedef-instead-of-anonymous-enum.patch
- uhdm-tests/black-parrot/Makefile.in
This PR extends CI with Black Parrot core.
Requires: https://github.com/chipsalliance/UHDM-integration-tests/pull/725
> CI: Add Black Parrot using unicore configuration to CI

- uhdm-tests/opentitan/opentitan_synth_patches/0018-Fix-some-out-of-range-access.patch
This patch was fixed by: https://github.com/chipsalliance/Surelog/issues/3614
> Remove unneeded ot patch

- .github/workflows/bsg-test-diff.yml
- .github/workflows/formal-verification.yml
- .github/workflows/large-designs.yml
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
It shouldn't be needed to use gcc-9 anymore.
> Remove usage of gcc-9

- .github/scripts/generate_summary.sh
- .github/scripts/run_group_test.sh
- .github/scripts/set-up-common-ubuntu-configuration.sh
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
- build_binaries.mk
- config/lsan.supp
- lib/fakedlclose/.gitignore
- lib/fakedlclose/Makefile
- lib/fakedlclose/fakedlclose.c
Adds a job that builds second set of binaries using clang with enabled address sanitizer.
Runs parsing tests using the tools with ASAN.
The results are printed to the summary and uploaded to artifacts.
Minor changes:
- Brief refactor of parsing tests' scripts
- Changed names of artifacts from parsing tests to include `parsing-tests_` prefix.
> CI: Enable ASAN

- formal/passlist.txt
- uhdm-tests/opentitan/opentitan_parsing_test/Makefile.scripts.sh
The new revision includes this PR: https://github.com/chipsalliance/yosys-f4pga-plugins/pull/521
> Bump plugins and fix minor bug in testing script

- .github/workflows/parsing-tests.yml
This PR fixes URL in PR message to AST logs difference between main branch.
> Fix URL to logs repository

- README.rst
To better reflect what this repo is.
> Update description in readme

- .github/workflows/large-designs.yml
- .github/workflows/main.yml
- build_binaries.mk
- frontends/systemverilog/Makefile
- tests/ibex/Makefile.in
- tests/opentitan/Makefile.in
- tests/opentitan/opentitan_synth_patches/0016_Update_python_requirements.txt.patch
- tests/veer/Makefile.in
Also, build other plugins only in the Ibex job.
> Do not use deprecated UHDM plugin in CI

- .github/workflows/parsing-tests.yml
Fixes CI issue where a certain step fails on PRs from forks (as seen in https://github.com/chipsalliance/synlig/pull/1970).
> Fix CI for external PRs

- images/synlig-logo.svg
This PR replaces the placeholder with the project's logo
> Add project logo

- .clang-format
- .github/scripts/format_sources.sh
- .github/workflows/main.yml
- frontends/systemverilog/uhdm_ast.cc
- frontends/systemverilog/uhdm_common_frontend.h
- frontends/systemverilog/uhdm_surelog_ast_frontend.cc
- frontends/systemverilog/utils/memory.h
- third_party/yosys_mod/const2ast.cc
- third_party/yosys_mod/const2ast.h
- third_party/yosys_mod/simplify.cc
- third_party/yosys_mod/simplify.h
> Add source formatting check

- frontends/systemverilog/Build.mk
> Make plugin build respect build type

- .github/workflows/large-designs.yml
To avoid situations like https://github.com/chipsalliance/synlig/commit/8932344c459f94a2c8a155989c01ddf0945ecdad
> Test OpenTitan 9d82960888 on pull requests

- tests/opentitan/0001_Add_opentitan_patch_for_uhdm.patch
This PR should fix connections in the generated dual port RAM in the OpenTitan test
> opentitan: update dual port ram generator

- frontends/systemverilog/uhdm_ast.cc
- tests/formal/passlist.txt
- tests/simple_tests/DotMultirangeSelect/top.sv
- tests/simple_tests/MemoryPort/top.sv
- tests/simple_tests/MultiAssignmentPatternOfConcat/top.sv
This fixes multiranges for wires that doesn't start with 0.
The PR has been moved here from https://github.com/chipsalliance/yosys-f4pga-plugins/pull/533
> fix convert_range function

- Makefile
These might not be easy to edit everywhere.
> Makefile: Remove unicode characters.

- .github/scripts/patch_yosys_config.sh
- .github/workflows/main.yml
Fixes #2164; see it for reasoning.
I only added the script to the GitHub builds since that's where the problem is most likely to manifest itself. Users building from source will likely specify the final installation path at compile time so this patch won't be necessary.
<details>
<summary>Patched yosys-config</summary>
```bash
#!/usr/bin/env bash
install_prefix="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
help() {
{
echo ""
echo "Usage: $0 [--exec] [--prefix pf] args.."
echo "       $0 --build modname.so cppsources.."
echo ""
echo "Replacement args:"
echo "    --cxx         c++"
echo "    --cxxflags    $( echo '-Wall -Wextra -ggdb -I"$install_prefix//share/yosys/include" -MD -MP -D_YOSYS_ -fPIC -I"$install_prefix"//include -std=c++11 -Os -DYOSYS_ENABLE_READLINE …
```
> Patch `yosys-config` to report accurate paths

- tests/formal/passlist.txt
> Bump yosys

- .github/workflows/bsg-test-diff.yml
- .github/workflows/cmake.yml
- .github/workflows/formal-verification.yml
- .github/workflows/large-designs.yml
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
This MR updates the runner tags so that they are more specific and with the accordance to https://github.com/antmicro/runner/commit/73a7c8fe4795d5a2f38376853309d2b659225fff.
> ci: update custom runners labels

- .ci.yml
- tests/simple_tests/BitsCallOnStructMember/yosys_script.tcl
- tests/simple_tests/EnumParameterInNestedModules/yosys_script.tcl
- tests/simple_tests/LogicPackedArray/yosys_script.tcl
- tests/simple_tests/MemoryPort/yosys_script.tcl
- tests/simple_tests/UnionCustomTypeMultirange/yosys_script.tcl
- tests/simple_tests/UnsizedConstant/yosys_script.tcl
- tests/simple_tests/UnsizedConstantParameter/yosys_script.tcl
- tests/simple_tests/UnsizedConstantParameterInInstance/yosys_script.tcl
- tests/simple_tests/array-copy/yosys_script.tcl
- tests/simple_tests/cs_registers/yosys_script.tcl
- tests/simple_tests/hier_path/yosys_script.tcl
This PR adapts tests script and updates yosys revision.
> Adjust tests script and update yosys revision

- .github/workflows/main.yml
- README.md
- frontends/systemverilog/uhdm_ast.cc
- tests/formal/passlist.txt
- tests/formal/skiplist.txt
- tests/simple_tests/MultirangeMemory/Makefile.in
- tests/simple_tests/MultirangeMemory/top.sv
- tests/simple_tests/MultirangeMemory/yosys_script.tcl
- third_party/yosys_mod/synlig_simplify.cc
Upstream yosys changed the way how it stores multidimensional ranges.
This commit adapts synlig internals to this change.
> Update yosys version to 0.39

- tests/ibex/Makefile.in
- tests/opentitan/Makefile.in
- tests/opentitan/opentitan_parsing_test/Makefile
- tests/veer/Makefile.in
Simplesat version 0.9.0 has broken wheel package, this PR forces installation of Simplesat version 0.8.2.
This should fix failing CI on main.
For more details check: https://github.com/enthought/sat-solver/issues/286
> Force installation of lower simplesat version

- src/main.cc
This PR updates prompt to `synlig>`.
> Update Synlig prompt

- .ci.yml
- .github/workflows/bsg-test-diff.yml
- .github/workflows/formal-verification.yml
- .github/workflows/large-designs.yml
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
- README.md
Now release package doesn't assume user have superuser privileges to install it.
Requires: https://github.com/chipsalliance/synlig/pull/2556
> Change format of release package

- .github/workflows/bsg-test-diff.yml
- .github/workflows/formal-verification.yml
- .github/workflows/large-designs.yml
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
The old versions are scheduled for deprecation.
> Bump upload-artifact and download-artifact versions

- src/Makefile
- src/main.cc
> Change Synlig exit message

- README.md
- src/frontends/systemverilog/uhdm_surelog_ast_frontend.cc
This PR updates `read_systemverilog` command message in the frontend and README guide
> [#65257] Update read_systemverilog command message

- .github/workflows/main.yml
- README.md
This PR also updates `README` with dependencies necessary to download release.
> Fix testing of downloading release from README

- .ci.yml
- .github/workflows/formal-verification.yml
- tests/scripts/run_formal.sh
This PR decreases formal verification logs size by packing only useful logs to artifacts.
> Decrease formal verification logs size

- .ci.yml
- .github/scripts/generate_summary.sh
- .github/scripts/run_group_test.sh
- .github/workflows/parsing-tests.yml
- tests/scripts/run_parsing.sh
- tests/yosys_common.tcl
Now parsing tests are performed on all build types.
> Refactor parsing tests CI

- .github/scripts/run_group_test.sh
- .github/workflows/formal-verification.yml
This PR reduces numer of not important diffs between PRs and fixes uploading `yosys.log`.
> Fix debug logs for parsing tests

- src/Makefile
- tests/formal/testlist.json
This PR adjusts Synlig Makefile to recent submodule changes
> Adjust Synlig Makefile to submodule changes

- src/frontends/systemverilog/uhdm_ast.cc
- tests/opentitan/opentitan_parsing_test/ot_cores_passlist.txt
> Fix setting up scope for parameter simplification

- src/frontends/systemverilog/uhdm_ast.cc
- src/frontends/systemverilog/uhdm_ast.h
- src/frontends/systemverilog/uhdm_ast_frontend.cc
- src/frontends/systemverilog/uhdm_ast_shared.h
- src/frontends/systemverilog/uhdm_common_frontend.cc
- src/frontends/systemverilog/uhdm_common_frontend.h
- src/frontends/systemverilog/uhdm_surelog_ast_frontend.cc
- src/frontends/systemverilog/utils/memory.h
- src/mods/yosys_ast/README
- src/mods/yosys_ast/synlig_const2ast.cc
- src/mods/yosys_ast/synlig_const2ast.h
- src/mods/yosys_ast/synlig_edif.cc
- src/mods/yosys_ast/synlig_edif.h
- src/mods/yosys_ast/synlig_simplify.cc
- src/mods/yosys_ast/synlig_simplify.h
- tests/formal/README.md
- tests/formal/results.py
- tests/formal/run.py
This PR updates naming to match `synlig`.
> Update outdated naming
