- uhdm-tests/opentitan/Makefile.in
- uhdm-tests/opentitan/custom_files/prim_ram_2p.v
Now Surelog doesn't require module definition to include its parameters.
This PR updates Surelog, yosys, edalize, yosys-symbiflow-plugins and adapts opentitan to do not parse library files containing definition of xilinx primitives.
> Remove parse of library files in Surelog

- build_binaries.sh
build-binaries.sh exited with non-zero exit code if the stack binary already existed.
> Reinstall stack if exists

- .github/workflows/main.yml
1. Full release and plugin release are uploaded in separate steps (as the action apparently only supports one file to be uploaded).
2. Now Yosys is installed with sudo on GH runner.
Signed-off-by: Krzysztof Bieganski <kbieganski@antmicro.com>
> Fix plugin-only release and CI

- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
This PR changes from using generic prim implementation to xilinx.
It also patches currently not working features.
> Use xilinx prim implementation

- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
This PR updates opentitan patch and adds workaroud for wrong generation of genscope modules in Surelog: https://github.com/chipsalliance/Surelog/issues/2623
> Update opentitan patch

- .github/workflows/main.yml
This PR adds an artifact containing system resource usage graphs that are generated automatically by runners.
Plots that were already present were moved to a separate step to keep them in one archive.
> Add resource usage graphs as CI artifacts

- .github/scripts/bisect.sh
- .github/scripts/common.sh
- .github/scripts/compare_ast.py
- .github/workflows/main.yml
- uhdm-tests/opentitan/0001-Add-opentitan-patch-for-uhdm.patch
This PR enables building ibex and opentitan bitstream using vivado and uploads bitstream to artifacts.
It also reverts opentitan to last know working version (with working bitstream on HW) and adds automatic bisect of opentitan (finding newest next working version) in CI.
> Build opentitan bitstream

- README.rst
- install_plugin.sh
Also create a symlink to uhdm.so for backwards compatibility.
This should be merged only if https://github.com/SymbiFlow/yosys-f4pga-plugins/pull/276 is merged.
> Update the installation script after plugin rename

- .github/workflows/main.yml
Add renamed plugin (`systemverilog.so`) to release. Install script expects both it and `uhdm.so` for backward compatibility.
> Fix plugin-only release

- .github/workflows/main.yml
Currently, all the pipelines in PRs seem to fail due to missing skbuild
dependency.
Signed-off-by: Tomasz Gorochowik <tgorochowik@antmicro.com>
> Update py dependencies

- build_binaries.sh
The path /bin/bash is not guaranteed to exist on a Posix system, but /usr/bin/env is.
Signed-off-by: Henner Zeller <h.zeller@acm.org>
> Fix hardcoded path to /bin/bash -> /usr/bin/env bash

- .github/workflows/main.yml
- README.rst
Adds `workflow_dispatch` trigger, with optional `plugins_branch` parameter (AKA input).
This will allow privileged users to start a workflow manually (through github web UI or gh cli tool) on any branch of this repo. Additionally, by specifying `plugins_branch` (again, in UI or gh cli) to a branch present in https://github.com/antmicro/yosys-f4pga-plugins/, it is possible to override revision of `yosys-symbiflow-plugins`. This way one can push a branch to `yosys-f4pga-plugins` and be able to test it in a workflow in `yosys-systemverilog` without creating a branch there.
Manually started tasks use custom titles on actions list:
In order, from top to bottom:
- started manually without setting `plugins_branch` using command:
`gh workflow run main --ref mglb/AddManualCITrigger`
- started …
> Add manual CI trigger.

- .github/scripts/generate_summary.sh
- .github/scripts/run_group_test.sh
- .github/workflows/main.yml
There is almost 800 jobs generated on each CI run at this moment, this PR introduces grouping of short tests which significantly lowers number of generated jobs. This change makes going through CI results easier for user and loading them should be more lightweight for GH servers.
> Optimize CI

- .github/workflows/main.yml
- formal/passlist.txt
We need more memory to run opentitan_synth, so we are changing the machine with 32G RAM to the one with 64G RAM.
> Change machine for opentitan_synth job

- .github/workflows/main.yml
Formal verification CI occasionally runs into OOM errors:
- https://github.com/antmicro/yosys-systemverilog/actions/runs/3692531494
- https://github.com/antmicro/yosys-systemverilog/actions/runs/3695295880
This PR changes the runner type to offer more memory.
> Change CI runner for formal verification

- formal/passlist.txt
This PR bumps submodules with the fix for signed wire in systemverilog plugin, spotted in the issue https://github.com/antmicro/yosys-systemverilog/issues/938, and a separate test for this fix.
> Signed wire fix

- .github/workflows/main.yml
- uhdm-tests/opentitan/iterate_cores.py
This fixes formatting, where two tables could be joined into one because a newline character was missing.
Also, the CI runs were very long due to the sizes of artifacts (`2min 23s` of processing OpenTitan, and then over `17 min` of uploading logs)
So, I'm removing all source files from the artifacts. This reduces the size of unpacked logs from 130M to 40M.
The whole job of `opentitan_parse_report` took 11min 58s with this change.
> Improve flow for OpenTitan

- .github/workflows/main.yml
- .github/workflows/tuttest.yml
Current release does not seem to work with singularity.
A better solution would be to switch to debian for most jobs (except the ones where we explicitly want to test ubuntu, e.g. the plugin installation on various distros)
> Temporarily freeze ubuntu to an older version

- .github/workflows/main.yml
This is only used by the custom runners. The release runs on a stock runner.
> Remove env from the release action

- .github/scripts/set-up-common-ubuntu-configuration.sh
- .github/workflows/main.yml
- .github/workflows/tuttest.yml
This adds a few US mirrors to the repository list, sets retry count to 6, and disables ipv6 (ubuntu servers have problems with it, and it is used by default).
The 4 non-ubuntu URLs were picked because they have highest throughput from all official US mirrors (20+ Gbps) according to https://launchpad.net/ubuntu/+archivemirrors.
Generally this works so that when the first mirror from the list fails, apt tries a next one.
> CI: Use Ubuntu mirrors & Revert to ubuntu:jammy container image.

- .github/workflows/tuttest.yml
This PR aims to fix failing tuttest on debian-sid (https://github.com/antmicro/yosys-systemverilog/actions/runs/4162797343/jobs/7202408929#step:4:1069):
```
11:10:39 | error: externally-managed-environment
11:10:39 | 
11:10:39 | × This environment is externally managed
11:10:39 | ╰─> To install Python packages system-wide, try apt install
11:10:39 |     python3-xyz, where xyz is the package you are trying to
11:10:39 |     install.
11:10:39 |     
11:10:39 |     If you wish to install a non-Debian-packaged Python package,
11:10:39 |     create a virtual environment using python3 -m venv path/to/venv.
11:10:39 |     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
11:10:39 |     sure you have python3-full installed.
11:10:39 |     
11:10:39 |     If you wish to install a …
```
> CI: use pipx instead of pip

- .github/workflows/tuttest.yml
Ref: https://github.com/antmicro/yosys-systemverilog/pull/1499#discussion_r1104506889
Setting ``GITHUB_PATH`` in custom-runners requires additional ``:`` at the end and it is confusing.
> CI: set PIPX_BIN_DIR instead of PATH

- .gitmodules
- uhdm-tests/ibex/top_artya7_core.patch
While implementing a block ram demo similar to one from Ibex, but using `read_verilog` instead of `read_systemverilog`, I had a problem with reproducing the issue my fix was intended to fix. In the demo Yosys was able to automatically truncate wires from 64 to 32 bit where necessary, which hasn't happened when building Ibex.
Turns out `synth_verilog` has been executed partially due to `-run :check` option. Without this option everything builds successfully with upstream Yosys.
> Change Yosys options used by Ibex & use upstream Yosys

- .github/scripts/generate_summary.sh
- .github/scripts/run_group_test.sh
When everything passed, the list of tests is initially folded.
[Live demo](https://github.com/antmicro/yosys-systemverilog/actions/runs/4258279850)
---
When there are failures, their list is initially visible. The separate list of passed tests is initially folded. Note: failures on the screenshot are made up and were artificially injected into test outputs just to show and test how it would look.
[Live demo](https://github.com/antmicro/yosys-systemverilog/actions/runs/4258278521)
---
Up until now there were two tables. Both with the same tests, but with results for different tool.
Now there's just one table, with results for both tools in separate columns.
> CI: Fold and merge tables in parsing tests results summary.

- .github/scripts/generate_summary.sh
Restores missing `read-uhdm` and `read-systemverilog` in the parsing tests summary table.
The bug has been introducent in #1539
> CI: Fix table headers.

- uhdm-tests/ibex/Makefile.in
Continuation of: https://github.com/antmicro/yosys-systemverilog/pull/1563
Previous PR removed only patch, but we were still trying to apply it. Now remove also code that is applying it.
> Remove no longer needed patch

- .github/scripts/set-up-common-ubuntu-configuration.sh
- .github/workflows/formal-verification.yml
- .github/workflows/main.yml
- build_binaries.sh
- Use 8-core machine for building
- The job downloads only submodules it needs, i.e. Yosys, Surelog, sv2v, yosys-f4pga-plugins.
- Sv2v building has been moved to its own job.
- It is used only by formal tests, the rest doesn't need to wait for it.
- Changes rarely, so the built binary is just cached using git revision as part of the cache key.
Workflow without cached sv2v: https://github.com/antmicro/yosys-systemverilog/actions/runs/4490034124/jobs/7896597216
Overall, in most cases, binaries built time changed from more than 10 min to about 5 min.
> CI: Speed up `build-binaries`

- .github/workflows/formal-verification.yml
- .github/workflows/large-designs.yml
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
- .github/workflows/tuttest.yml
The Github itself offers an option to show timestamps on demand, and they are always present in log dumps. The only added value of the Runner-generated timestamp has been indication (with a color) whether the line has been printed to the stdout or the stderr. A single `▌` does this job as well, and leaves more horizontal space for actual content.
The option to show timestamps is in the gear menu:
View "main" CI logs for this PR to see an example, e.g. https://github.com/antmicro/yosys-systemverilog/actions/runs/4720484169/jobs/8372587488#step:5:2
> CI: Use `▌` instead of a timestamp in console output.

- .github/workflows/large-designs.yml
This job takes more than 4h to complete. We are also testing another opentitan version in PR CI.
> CI: run pinned opentitan synth only on main branch

- .github/workflows/formal-verification.yml
- .github/workflows/large-designs.yml
- .github/workflows/parsing-tests.yml
Black-parrot SDK has really huge submodules (buildroot, linux kernel, yocto) which we don't use. Fetching of those submodules added a few minutes to each CI job.
Instead of always recursively fetching everything, each job now pulls only submodules it needs.
Checkout (+ "Checkout submodules") durations before and after:
| Job                             | Checkout before | Checkout after |
|---------------------------------|-----------------|----------------|
| parsing/*                       |           04:52 |          00:31 |
| formal verification/*           |           04:59 |          00:12 |
| large designs/ibex              |           05:00 |          00:16 |
| large designs/opentitan (synth) |           04:48 |          00:11 |
| large designs/opentitan parsing |           04:54 …
> CI: Fetch only required submodules.

- .github/workflows/large-designs.yml
Ibex Vivado synthesis started failing because of missing packages. Here's an example job that failed: https://github.com/antmicro/yosys-systemverilog/actions/runs/4891230300/jobs/8735612232. This PR adds these packages.
> Install pkg-config and libcairo2-dev for ibex_synth job

- .github/scripts/submodule-revision-override.inc.bash
- .github/workflows/formal-verification.yml
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
- README.rst
`uhdm_tests_branch` can be used in the same way as `plugins_branch` to specify submodule override for UHDM-integration tests.
The `plugins_branch` and `uhdm_tests_branch` support 3 formats:
- `<REVISION>` - already known, uses `<REVISION>` from Antmicro's fork.
- `https://github.com/<USER>/<REPO>/tree/<REVISION>`
- `/<USER>/<REPO>/tree/<REVISION>` (note `/` at the beginning)
The new formats aren't random - this is an URL of a revision file view. This is where GH points to after clicking "Browse files" button in commits, selecting a branch in a drop-down, or clicking branch name under PR title.
Example: https://github.com/chipsalliance/yosys-f4pga-plugins/tree/a08c529a86a525fc4278221a5599a2e783c8105e
Shows exactly what revisions of plugins and tests were used in the workflow:
Please ignore …
> CI: Add support for workflow_dispatch with external custom submodules

- .github/workflows/tuttest.yml
- README.rst
Similar thing that was done in: https://github.com/antmicro/yosys-systemverilog/pull/1674 but this time for tuttest jobs.
> CI: reduce submodules checkout time in tuttest jobs

- .github/scripts/push_to_another_repository.sh
- .github/scripts/push_to_logs_repository.sh
- .github/scripts/run_group_test.sh
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
This PR adds new CI jobs that pushes AST to ``yosys-systemverilog-logs`` repository. This allows to easily view diff of AST between introduced changes.
URL with diff is posted as both github actions summary as well as PR comment (when event is pull_request).
Currently it only works when submodules are override using branches instead of whole url.
> CI: add job storing AST results in different repository

- .github/scripts/push_to_logs_repository.sh
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
This PR fixes several issues with push AST diff job:
- adds ``yosys-f4pga-plugins`` and ``UHDM-test-integration`` branch to concurrency when run is triggered by workflow call.
- fixes new line in comment message and github summary
- replaces only source directory in target repository to allow README or workflow files in target repository
> CI: fix several issues with push AST diff job

- .github/dependabot.yml
During the work on PR #1732, we moved `bsg_micro_designs` submodule to `uhdm-tests/bsg_micro_designs` catalogue but didn't update the dependabot config file. Here's a followup.
> dependabot.yml: Update dependency name to be ignored

- .github/workflows/large-designs.yml
- uhdm-tests/black-parrot/Makefile.in
- uhdm-tests/black-parrot/black-parrot-patches/black-parrot/0001-use-synth-filelist.patch
This PR adds ``-DSYNTHESIS=1`` to surelog command to make sure synthesis path is used in the code.
This RP also replaces on of the files for it's synthesis compatible version: https://github.com/black-parrot/black-parrot/blob/4ae2e5af2bdf1860581c15826a12eab59a381eb2/bp_common/syn/tcl/vivado_synth.tcl#L26
> Build blackparrot with SYNTHESIS=1

- .github/workflows/bsg-test-diff.yml
- uhdm-tests/bsg_micro_designs/generate_bsg_tests.py
Parameters that are used in the tests are taken from first configuration inside `.json` files present in [bsg_micro_designs](https://github.com/bsg-idea/bsg_micro_designs/tree/c7143611f86e9eaec98c6ac3935147817f2221a0/bsg_async/bsg_async_credit_counter) submodule. To be clear, what values are set for the parameters, we'd like to write them to a file for each generated `dut.v`.
> generate_bsg_tests: Write parameters to a file for each test

- .github/workflows/main.yml
Moving date to the beginning of the tag makes it easier to sort and detect changes.
Closes: #1798
> Update tags/releases format

- .github/workflows/main.yml
- .github/workflows/tuttest.yml
SID is unstable, which means it gets untested packages. Recently yosys package has appeared in SID even though it failed Debian's automatic regression tests.
Let's go with a stable release, like we do with Ubuntu.
> CI: Use latest stable Debian instead of SID.

- .gitmodules
Leftover from https://github.com/chipsalliance/systemverilog-plugin/pull/1906
> Remove SweRV from `.gitmodules`

- .github/workflows/parsing-tests.yml
Now we can't override submodules branches and we can always calculate correct name branch name in logs repository
> Always enable pushing logs

- .github/workflows/parsing-tests.yml
Now, default branch name is ``main``.
> Update default branch name of logs repository

- .github/scripts/run_group_test.sh
The string that is used in sed to cut the interesting part of a log is not supposed to be the same with all the PARSER options. With `PARSER=surelog` it should be `"Executing UHDM frontend"`, while with `PARSER=yosys-plugin` it should be `"Executing Verilog with UHDM frontend"`.
This caused the logs to be empty in one configuration.
> Process log files properly when using PARSER=Surelog

- install_plugin.sh
`uhdm.so` is no longer being built.
> Remove `uhdm.so` from install script

- .github/workflows/tuttest.yml
- README.md
- build_binaries.sh
This PR removes Ubuntu from the README and CI. Also it migrates the source test from Ubuntu to debian:bookworm. This is because we will soon require newer Yosys and only debian (that will be updated to trixie once we bump yosys submodule) contains new enough version.
> Remove Ubuntu from README and CI

- .gitignore
- frontends/systemverilog/uhdm_ast.cc
- frontends/systemverilog/uhdm_ast.h
- tests/formal/passlist.txt
Some tests would fail in the automatic PR to bump Surelog:
https://github.com/chipsalliance/synlig/actions/runs/6172468338/job/16753192588?pr=1965
There was an unhandled case in the switch in `process_object`. With this PR it's solved.
I'm also adding files to the `.gitignore` file assuming that such a change doesn't need a separate PR. Please let me know if other solution is preferred.
> Bump surelog

- build_binaries.sh
Related to https://github.com/chipsalliance/synlig/commit/d7d16c325d55b01e7bd06603420402ff885408a2. Submodules were moved to the `third_party` directory. Paths in `build_binaries.sh` were updated for Surelog and Yosys but not for sv2v.
> Fix `sv2v` path after moving submodule to `third_party`

- .github/workflows/main.yml
Migrate the build step to Debian.
This is a follow up to #1993
> CI: Build release images on debian

- frontends/systemverilog/uhdm_ast.cc
Handle introduction of ref_typespec in UHDM/Surelog
chipsalliance/UHDM#1022
chipsalliance/Surelog#3868
> Handle introduction of ref_typespec in UHDM/Surelog

- .github/workflows/bsg-test-diff.yml
- .github/workflows/formal-verification.yml
- .github/workflows/large-designs.yml
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
- .github/workflows/tuttest.yml
- .gitmodules
- README.md
Only yosys and surelog submodules are needed for plugin build. Those two are automatically fetched as before, i.e. after calling just `git submodule update --recursive`.
All other submodules are skipped, even when their paths are explicitly specified. To fetch them one has to add `--checkout` flag has to `git submodule update`, e.g.:
```
git submodule update --dept 1 --init --recursive --checkout
```
Fixes #1962
> Do not pull non-essential submodules by default.

- frontends/systemverilog/uhdm_ast.cc
- frontends/systemverilog/uhdm_ast.h
- tests/formal/passlist.txt
- tests/simple_tests/EnumItemReimport/Makefile.in
- tests/simple_tests/EnumItemReimport/top.sv
- tests/simple_tests/EnumItemReimport/yosys_script.tcl
Fixes #1988.
The error is caused by the enum being added during the iteration of the design, and then again during the iteration of `uhdmtopModules`. Because the original enum is added at the top level, we don't see it so we add it again to individual modules.
Instead of adding typedefs at the top level, this patch makes it so we add it to each top module. Same thing with top-level parameters, as they may require these typedefs.
> Fix enum item redeclaration error on reimport

- tests/formal/results.py
Currently the path is incorrect and clicking it results in a 404.
> Fix path to formal verification README in summary

- frontends/systemverilog/Build.mk
- frontends/systemverilog/uhdm_common_frontend.cc
- frontends/systemverilog/uhdm_common_frontend.h
- third_party/yosys_mod/edif.cc
- third_party/yosys_mod/edif.h
This allows us to use latest yosys. The upstream edif pass introduced
changes which are incompatible with SystemVerilog.
This should unblock #2008
> Custom edif backend

- .github/workflows/main.yml
This patch makes the plugin path in the Debian tarball identical to the one in the non-Debian package.
> Fix Debian tarball path

- .github/workflows/main.yml
- install_plugin.sh
Yosys packaged for Debian > 12 expects plugins in a different directory than the one given by `yosys-config`.
> Fix plugin install path on Debian

- Makefile
- build_binaries.mk
- run_fv_tests.mk
- tests/lib/testhandlers/formalverification.py
- tests/list.py
- tests/opentitan/opentitan_parsing_test/Makefile
- tests/opentitan/opentitan_parsing_test/Makefile.scripts.sh
Bash is not always located /bin/bash
In Makefiles, use just 'bash' so that it is found from the path; also make it possible to override on the command line if needed.
Replace #!/bin/bash in scripts with #!/usr/bin/env bash
Also fix one instance of #!/usr/bin/python to #!/usr/bin/env python
> Don't hardcode location of bash and python

- frontends/systemverilog/Build.mk
There is no --export-dynamic linker option on clang11 on Darwin, so compile fails there with
```
ld: unknown option: --export-dynamic
```
Without this option, the plug-in works as well, so remove it.
> Remove linker option that fails on Mac/Darwin

- CMakeLists.txt
The new CMake-based build system almost works on macOS, but fails at the final step when linking the plugin. This is because the default behavior on macOS (for both clang and GCC) is to require all symbols to be defined at link time for a dynamic library. This is not the case for synlig, so it fails to link.
<details>
<summary>Failing linker output</summary>
```
[100%] Linking CXX shared library /opt/synlig/install/share/yosys/plugins/systemverilog.dylib
ld: warning: ignoring duplicate libraries: 'third_party/surelog/third_party/UHDM/lib/libuhdm.a'
ld: Undefined symbols:
Yosys::log_header(Yosys::RTLIL::Design*, char const*, ...), referenced from:
systemverilog_plugin::UhdmAstFrontend::call_log_header(Yosys::RTLIL::Design*) in uhdm_ast_frontend.cc.o …
```
> Fix CMake build on macOS

- frontends/systemverilog/compat_symbols.cc
- frontends/systemverilog/uhdm_common_frontend.cc
This uses a weak symbol which allows us to build and link with Yosys before and after the API change.
Ref: #2300
> Introduce a compatibility layer for Yosys::AST::process

- .github/workflows/main.yml
See if we can run them on debian:sid, the yosys package is still available there.
> Restore the packaged yosys tests

- .github/workflows/parsing-tests.yml
Currently logs are only pushed on pull request event.
This means, logs are not updated on main branch after pull request merge.
> Run AST diff job on push event

- .github/scripts/set-up-common-debian-configuration.sh
- .github/scripts/set-up-common-git-configuration.sh
- .github/workflows/bsg-test-diff.yml
- .github/workflows/formal-verification.yml
- .github/workflows/large-designs.yml
- .github/workflows/main.yml
- .github/workflows/parsing-tests.yml
This PR adds script to setup debian mirrors to limit CI failures due to connection errors with debian repository mirrors.
> Add debian mirrors

- .github/workflows/main.yml
Github requires `contents: write` permission to create release: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
> Add missing permissions for release job

- .github/workflows/cmake.yml
This should lower number of failed CI jobs due to rate-limit on debian mirror
> Add debian mirrors to cmake job

- .ci.yml
- frontends/systemverilog/uhdm_ast.cc
- frontends/systemverilog/uhdm_ast.h
- tests/formal/passlist.txt
- tests/formal/skiplist.txt
- tests/simple_tests/EnumInGenblock/Makefile.in
- tests/simple_tests/EnumInGenblock/top.sv
- tests/simple_tests/EnumInGenblock/yosys_script.tcl
- tests/simple_tests/GenblockAlwaysFor/Makefile.in
- tests/simple_tests/GenblockAlwaysFor/top.sv
- tests/simple_tests/GenblockAlwaysFor/yosys_script.tcl
- tests/simple_tests/GenblockPackedAccess/Makefile.in
- tests/simple_tests/GenblockPackedAccess/top.sv
- tests/simple_tests/GenblockPackedAccess/yosys_script.tcl
- tests/simple_tests/MultipleNestedStructs/Makefile.in
- tests/simple_tests/MultipleNestedStructs/top.sv
- tests/simple_tests/MultipleNestedStructs/yosys_script.tcl
- tests/simple_tests/NestedStructs/Makefile.in
- tests/simple_tests/NestedStructs/top.sv
- tests/simple_tests/NestedStructs/yosys_script.tcl
- tests/simple_tests/PackedInGenblock/Makefile.in
- tests/simple_tests/PackedInGenblock/top.sv
- tests/simple_tests/PackedInGenblock/yosys_script.tcl
- tests/simple_tests/ScopeOverwriting/Makefile.in
- tests/simple_tests/ScopeOverwriting/top.sv
- tests/simple_tests/ScopeOverwriting/yosys_script.tcl
- third_party/yosys_mod/synlig_simplify.cc
- third_party/yosys_mod/synlig_simplify.h
This PR updates yosys and adjusts synlig to it:
* rework the way, that synlig handles AST_GENBLOCK's,
* allow typedefing nested structs and unions inside AST_GENBLOCK's,
* add new simple tests,
* minor bugfixes.
> Update yosys; rework AST_GENBLOCK's handling

- frontends/systemverilog/uhdm_ast.cc
- third_party/yosys_mod/synlig_const2ast.cc
- third_party/yosys_mod/synlig_const2ast.h
- third_party/yosys_mod/synlig_simplify.cc
- third_party/yosys_mod/synlig_simplify.h
This PR ensures that all functions in `yosys_mod.cc` are prefixed with `synlig_`.
It also makes sure that code from `yosys_mod` calls functions (if available) from `yosys_mod`, not directly from yosys.
> Unify functions naming in yosys_mod and remove unnecessary calls to yosys functions

- .github/workflows/main.yml
- README.md
- tests/opentitan/0001_Add_opentitan_patch_for_uhdm.patch
- third_party/Build.yosys.mk
- third_party/yosys_mod/synlig_simplify.cc
This commit also disables creating `$scopeinfo` cells in large designs tests.
`$scopeinfo` is Yosys internal cell and should be removed before passing netlist to another tool.
> Update yosys version to 0.44

- .ci.yml
- .github/workflows/parsing-tests.yml
- frontends/systemverilog/uhdm_ast.cc
- frontends/systemverilog/uhdm_ast.h
- frontends/systemverilog/uhdm_ast_shared.h
- tests/formal/passlist.txt
- tests/formal/run.py
- tests/formal/skiplist.txt
- tests/simple_tests/ParameterPackedArray/yosys_script.tcl
- tests/simple_tests/ParameterUnpackedArray/yosys_script.tcl
- tests/simple_tests/ParameterUnpackedLogicArray/yosys_script.tcl
uhdmallModules contains unelaborated tree. To simplify processing, we can visit only uhdmtopModules that contains already elaborated tree.
Before this change, we were visiting both trees and replacing unelaborated nodes with elaborated that are present in uhdmtopModules.
> Visit only uhdmtopModules

- tests/formal/results.py
- tests/formal/run.py
Currently formal verification script `results.py` is only returning value that should be exit code, but it always exits with 0.
This PR fixes this.
We also noticed some issue with Surelog cache in formal verification, so as a workaround, we are disabling it temporarily.
> Fix exit code in Formal Verification results.py

- tests/opentitan/0001_Add_opentitan_patch_for_uhdm.patch
This pass takes about ~4h to process OpenTitan 9d82960888 modules, but it only checks for obvious problems, it doesn't transform netlist.
> Skip `check` pass in `synth_xilinx` for OpenTitan 9d82960888

- tests/formal/gather_fv_results.sh
- tests/formal/results.py
This PR changes formal verification script to fail when it will detect any difference in expected output. It also checks if all tests present in testlist were performed.
> Fail CI on every result difference

- .ci.yml
- .github/workflows/main.yml
- README.md
This PR refactors verifying `README` with `tuttest`. Now CI:
- checks Synlig and tools installation from `README`,
- checks `README` examples,
- verifies downloadable release correctness.
This PR also removes some deprecated `README` tests.
> Update testing README with tuttest

- .ci.yml
- .github/workflows/main.yml
- .gitignore
- Makefile
- README.md
- src/Build.synlig.mk
- src/Makefile
- src/Makefile.inc
- src/frontends/systemverilog/Makefile.inc
- src/mods/yosys_ast/Makefile.inc
This PR removes usage of `.NOTPARALLEL` that isn't supported in every `make` version and instead properly defines dependencies between targets.
> Make synlig build/install depend on surelog

- .ci.yml
- .github/workflows/main.yml
This commit addresses the fact that each run section is performed in different bash. It also adds `-e` and `-o pipefail` to make sure we will properly fail CI while testing.
> Fix testing README with tuttest

- README.md
This PR makes sure that all codeblocks in README have the same indention.
> Unify README indentation

- .github/workflows/parsing-tests.yml
This PR fixes pushing tests logs after merge to allow visualize changes in AST in PRs.
> Fix pushing logs to main branch of synlig-logs repo

- src/frontends/systemverilog/uhdm_ast.cc
- tests/formal/testlist.json
Now Synlig supports accessing multidimensional struct members.
> Refactor converting AST_DOT to range selects

- src/frontends/systemverilog/uhdm_ast.cc
This PR addresses: https://github.com/chipsalliance/synlig/issues/2647
> Fix overwriting typedef name when processing packed enum

- CMakeLists.txt
- Makefile
- src/Makefile
- src/frontends/systemverilog/Build.mk
- src/frontends/systemverilog/Makefile.inc
- src/mods/yosys_ast/Makefile.inc
- src/mods/yosys_ast/synlig_edif.cc
- src/mods/yosys_ast/synlig_simplify.cc
- src/mods/yosys_ast/synlig_write_ilang.cc
- src/yosys_patches/0001-Fix-setting-undef-bits-in-parameters.patch
- src/yosys_patches/Makefile.inc
- tests/formal/testlist.json
This PR updates yosys.
It also applies patch to yosys until: https://github.com/YosysHQ/yosys/pull/4733 will be merged upstream.
> Adjust Synlig to recent Yosys changes

- CMakeLists.txt
- src/frontends/systemverilog/Build.mk
- src/frontends/systemverilog/uhdm_common_frontend.cc
- src/mods/yosys_ast/Makefile.inc
- src/mods/yosys_ast/synlig_ilang.cc
- src/mods/yosys_ast/synlig_ilang.h
> Add alias for write_rtlil only when ilang frontend doesn't exist

- src/frontends/systemverilog/uhdm_ast.cc
This PR fixes segmentation fault seen in this issue: https://github.com/chipsalliance/Surelog/issues/4017, but it doesn't fix the actual problem with missing `vpiActual` in UHDM tree.
> Add check for nullptr dereference in process_port

- src/utils/main.cc
Fixes: https://github.com/chipsalliance/synlig/issues/2669
Fragment of help message:
```
-L logfile
like -l but open log file in line buffered mode
-o outfile
write the design to the specified file on exit
-b backend
use this backend for the output file specified on the command line
list of available backends: aiger, blif, btor, cxxrtl, edif, firrtl,
ilang, intersynth, jny, json, rtlil, simplec, smt2, smv, spice, table,
test_autotb, verilog, xaiger
-f frontend
use the specified frontend for the input files on the command line
list of available frontends: aiger, blif, ilang, json, liberty, rtlil,
systemverilog, uhdm, verilog, verilog_with_uhdm, write_file, xaiger2
-H
print the command list
-h command
print the help message for the specified command
-s scriptfile
execute the commands in the …
```
> Print available frontends and backends list when running synlig --help
